<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-ERPL0N8" failures="1" tests="3" name="com.crowdar.bdd.cukes.TestNGSecuencialRunner" time="438.368" errors="0" timestamp="09 mar. 2022 20:46:19 GMT" skipped="0">
  <testcase classname="com.crowdar.bdd.cukes.TestNGSecuencialRunner" name="runScenario" time="56.836"/>
  <testcase classname="com.crowdar.bdd.cukes.TestNGSecuencialRunner" name="runScenario" time="309.562"/>
  <testcase classname="com.crowdar.bdd.cukes.TestNGSecuencialRunner" name="runScenario" time="71.970">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at lippia.web.services.AutomationService.verifyResults(AutomationService.java:69)
at lippia.web.steps.AutomationWebSteps.theClientVerifyThatResultsAreShownProperly(AutomationWebSteps.java:61)
at âœ½.The client verify that results are shown properly.(file:src/test/resources/web/features/AutomationPractice.feature:23)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- com.crowdar.bdd.cukes.TestNGSecuencialRunner -->
