<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-ERPL0N8" failures="1" tests="3" name="com.crowdar.bdd.cukes.TestNGSecuencialRunner" time="71.754" errors="0" timestamp="09 feb. 2022 15:53:16 GMT" skipped="0">
  <testcase classname="com.crowdar.bdd.cukes.TestNGSecuencialRunner" name="runScenario" time="16.713">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at lippia.web.services.AutomationHomeService.verifyResults(AutomationHomeService.java:65)
at lippia.web.steps.AutomationWebSteps.theClientVerifyThatResultsAreShownProperly(AutomationWebSteps.java:63)
at âœ½.The client verify that results are shown properly.(file:src/test/resources/web/features/AutomationPractice.feature:23)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="com.crowdar.bdd.cukes.TestNGSecuencialRunner" name="runScenario" time="36.812"/>
  <testcase classname="com.crowdar.bdd.cukes.TestNGSecuencialRunner" name="runScenario" time="18.229"/>
</testsuite> <!-- com.crowdar.bdd.cukes.TestNGSecuencialRunner -->
