<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-ERPL0N8" failures="1" tests="3" name="TestNg Secuencial runner Tests" time="281.941" errors="0" timestamp="13 mar. 2022 23:27:25 GMT">
  <testcase classname="cucumber.api.testng.AbstractTestNGCucumberTests" name="runScenario" time="118.404"/>
  <testcase classname="cucumber.api.testng.AbstractTestNGCucumberTests" name="runScenario" time="101.995"/>
  <testcase classname="cucumber.api.testng.AbstractTestNGCucumberTests" name="runScenario" time="54.648">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at lippia.web.services.PageSearchResultService.verifyResults(PageSearchResultService.java:55)
at lippia.web.steps.AutomationWebSteps.theClientVerifyThatResultsAreShownProperly(AutomationWebSteps.java:45)
at âœ½.The client verify that results are shown properly.(file:src/test/resources/web/features/AutomationPractice.feature:23)
... Removed 4 stack frames]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- TestNg Secuencial runner Tests -->
